---
title: "polimp_analysis_EYMCF"
author: "Erica Yoon"
date: "April 1, 2015"
output: html_document
---

```{r}
rm(list = ls())
library(jsonlite)
library(ggplot2)
library(tidyr)
source("../helper/useful.R")

raw.data.path <- "../../production-results/v1"

## LOOP TO READ IN FILES
all.data <- data.frame()
files <- dir(raw.data.path,pattern="*.json")

for (file.name in files) {
  print(file.name)
  
  ## these are the two functions that are most meaningful
  json_file <- readLines(paste(raw.data.path,file.name,sep=""))
  json_file_str = paste(json_file, collapse = "")
  json_file_str = gsub(",}", "}", json_file_str)
  jso = jsonlite::fromJSON(json_file_str)
  jso1 <- data.frame(jso)
  jso1$subid <- substring(file.name, 1, 6)
  
  ## now here's where data get bound together
  all.data <- rbind(all.data, jso1)
}
```

Filter out participants and clean up.

```{r}
d <- all.data %>%
  select(subid, answer.scale, answer.judgment) %>%
  rename(judgment = answer.judgment) %>%
  filter(answer.scale != "training1" & answer.scale != "training2") %>%
  separate(answer.scale, into = c("utterance", "inference"), sep = "_") 

d$inference <- as.factor(d$inference)

d1 <- d %>%
  mutate(bound = factor(substring(inference, 1, 3),
                           levels = c("and", "but"),
                           labels = c("lower", "upper")),
         scale = factor(as.numeric(grepl("some", utterance)), 
                        levels = c(0, 1), 
                        labels = c("ad-hoc","scalar")),
         utt_valence = factor(as.numeric(grepl("love", utterance, 
                                               ignore.case=TRUE)), 
                            levels = c(0, 1), 
                            labels = c("hate", "love")),
         condition = str_c(utt_valence, "-", inference))
```

# Scalar inferences

```{r}
qplot(judgment, fill = condition, position = "dodge", 
      data = filter(d1, scale == "scalar")) + 
  facet_grid(~bound)
```

# Ad hocs

```{r}
qplot(judgment, fill = bound, position = "dodge", 
      data = filter(d, scale == "ad-hoc")) + 
  facet_grid(~condition)
```