---
title: "polimp ver 4 analysis"
author: "EJY, MCF"
date: "April 1, 2015"
output: html_document
---

Ver 4: "some people liked / disliked your poem" -> "do you think it is possible that everyone liked / disliked your poem?"

```{r warning=FALSE, message=FALSE}
rm(list = ls())
library(jsonlite)
library(ggplot2)
library(tidyr)
library(binom)
source("/Users/ericang/Documents/Research/Politeness/experiment/2_code/data_analysis/helper/useful.R")

raw.data.path <- "/Users/ericang/Documents/Research/Politeness/experiment/2_code/production-results/"

## LOOP TO READ IN FILES
v3 <- data.frame()
files <- dir(paste0(raw.data.path,"v3/"),pattern="*.json")

for (file.name in files) {
  print(file.name)
  
  ## these are the two functions that are most meaningful
  json_file <- readLines(paste(raw.data.path,"v3/",file.name,sep=""))
  json_file_str = paste(json_file, collapse = "")
  json_file_str = gsub(",}", "}", json_file_str)
  jso = jsonlite::fromJSON(json_file_str)
  jso1 <- data.frame(jso)
  jso1$subid <- substring(file.name, 1, 6)
  jso1$expt <- "v3"
  
  ## now here's where data get bound together
  v3 <- rbind(v3, jso1)
}

v4 <- data.frame()
files <- dir(paste0(raw.data.path,"/v4"),pattern="*.json")

for (file.name in files) {
  print(file.name)
  
  ## these are the two functions that are most meaningful
  json_file <- readLines(paste(raw.data.path,"v4/",file.name,sep=""))
  json_file_str = paste(json_file, collapse = "")
  json_file_str = gsub(",}", "}", json_file_str)
  jso = jsonlite::fromJSON(json_file_str)
  jso1 <- data.frame(jso)
  jso1$subid <- substring(file.name, 1, 6)
  jso1$expt <- "v4"
  
  ## now here's where data get bound together
  v4 <- rbind(v4, jso1)
}

all.data <- rbind(v3, v4)
```

Filter out participants and clean up.

```{r}
d <- all.data %>%
  select(subid, expt, answer.scale, answer.judgment) %>%
  rename(judgment = answer.judgment) %>%
  filter(answer.scale != "training1" & answer.scale != "training2") %>%
  separate(answer.scale, into = c("utterance", "inference"), sep = "_") 

d$inference <- as.factor(d$inference)

d1 <- d %>%
  mutate(bound = factor(substring(inference, 1, 3),
                           levels = c("and", "but"),
                           labels = c("lower", "upper")),
         scale = factor(as.numeric(grepl("some", utterance)), 
                        levels = c(0, 1), 
                        labels = c("ad-hoc","scalar")),
         utt_valence = factor(as.numeric(grepl("love", utterance, 
                                               ignore.case=TRUE)), 
                            levels = c(0, 1), 
                            labels = c("hate", "love")),
         condition = str_c(utt_valence, "-", inference))
```

```{r}
ms <- d1 %>%
  group_by(expt, condition) %>%
  mutate(n.total = n()) %>%
  group_by(expt, condition, judgment) %>%
  summarize(n = n(),
            n.total = n.total[1],
            mean = n / n.total,
            cih = binom.bayes(n, n.total)$lower,
            cil = binom.bayes(n, n.total)$upper)

qplot(condition, mean, ymax=cih, ymin=cil, 
      fill = judgment, 
      stat="identity", position=position_dodge(width=.9),
      geom=c("bar","linerange"),
      data=ms) + 
  facet_wrap(~expt) +
  ylab("Proportion of judgments") + 
  ylim(c(0,1)) + 
  geom_hline(yintercept=.5, lty=2) +
  ggtitle("liked vs. disliked") +
  scale_x_discrete(labels=
                     c("some dislike-> 
                       everyone dislike?", 
                       "some like-> 
                       everyone like?"))
```

```{r}
d_table <- table(d1$condition, d1$judgment)
chisq.test(d_table)

# a mixed model predicting participants' response as a function of condition and experiment
lmer <- glmer(judgment ~ expt * condition + (condition|subid), family=binomial, data=d1)
summary(lmer)
```