---
title: "polimp ver 3,4 analysis"
author: "EJY, MCF"
date: "April 13, 2015"
output: html_document
---

```{r warning=FALSE, message=FALSE}
rm(list = ls())
library(jsonlite)
library(ggplot2)
library(tidyr)
library(binom)
source("/Users/ericang/Documents/Research/Politeness/experiment/2_code/data_analysis/helper/useful.R")

raw.data.path <- "/Users/ericang/Documents/Research/Politeness/experiment/2_code/production-results/"

## LOOP TO READ IN FILES
brp <- data.frame()
files <- dir(paste0(raw.data.path,"bonnefon_rp/"),pattern="*.json")

for (file.name in files) {
  print(file.name)
  
  ## these are the two functions that are most meaningful
  json_file <- readLines(paste(raw.data.path,"bonnefon_rp/",file.name,sep=""))
  json_file_str = paste(json_file, collapse = "")
  json_file_str = gsub(",}", "}", json_file_str)
  jso = jsonlite::fromJSON(json_file_str)
  jso1 <- data.frame(jso)
  jso1$subid <- substring(file.name, 1, 6)
  jso1$expt <- "brp"
  
  ## now here's where data get bound together
  brp <- rbind(brp, jso1)
}

v3 <- data.frame()
files <- dir(paste0(raw.data.path,"v3/"),pattern="*.json")

for (file.name in files) {
  print(file.name)
  
  ## these are the two functions that are most meaningful
  json_file <- readLines(paste(raw.data.path,"v3/",file.name,sep=""))
  json_file_str = paste(json_file, collapse = "")
  json_file_str = gsub(",}", "}", json_file_str)
  jso = jsonlite::fromJSON(json_file_str)
  jso1 <- data.frame(jso)
  jso1$subid <- substring(file.name, 1, 6)
  jso1$expt <- "v3"
  
  ## now here's where data get bound together
  v3 <- rbind(v3, jso1)
}

v4 <- data.frame()
files <- dir(paste0(raw.data.path,"/v4"),pattern="*.json")

for (file.name in files) {
  print(file.name)
  
  ## these are the two functions that are most meaningful
  json_file <- readLines(paste(raw.data.path,"v4/",file.name,sep=""))
  json_file_str = paste(json_file, collapse = "")
  json_file_str = gsub(",}", "}", json_file_str)
  jso = jsonlite::fromJSON(json_file_str)
  jso1 <- data.frame(jso)
  jso1$subid <- substring(file.name, 1, 6)
  jso1$expt <- "v4"
  
  ## now here's where data get bound together
  v4 <- rbind(v4, jso1)
}

v5 <- data.frame()
files <- dir(paste0(raw.data.path,"/v5"),pattern="*.json")

for (file.name in files) {
  print(file.name)
  
  ## these are the two functions that are most meaningful
  json_file <- readLines(paste(raw.data.path,"v5/",file.name,sep=""))
  json_file_str = paste(json_file, collapse = "")
  json_file_str = gsub(",}", "}", json_file_str)
  jso = jsonlite::fromJSON(json_file_str)
  jso1 <- data.frame(jso)
  jso1$subid <- substring(file.name, 1, 6)
  jso1$expt <- "v5"
  
  ## now here's where data get bound together
  v5 <- rbind(v5, jso1)
}

all.data <- rbind(brp, v3, v4, v5)
```

Filter out participants and clean up.

```{r}
d <- all.data %>%
  select(subid, expt, answer.scale, answer.judgment) %>%
  rename(judgment = answer.judgment) %>%
  filter(answer.scale != "training1" & answer.scale != "training2") 


d1 <- d %>%
  mutate(valence = factor(as.numeric(grepl("love", answer.scale, 
                                               ignore.case=TRUE)), 
                            levels = c(0, 1), 
                            labels = c("hate", "love")),
         context = factor(as.numeric(grepl("noUtterance", answer.scale,
                                           ignore.case=TRUE)),
                          levels = c(0, 1),
                          labels = c("Utterance", "noUtterance"))
         )
```

```{r}
ms <- d1 %>%
  filter(context == "Utterance") %>%
  group_by(expt, valence) %>%
  mutate(n.total = n()) %>%
  group_by(expt, valence, judgment) %>%
  summarize(n = n(),
            n.total = n.total[1],
            mean = n / n.total,
            cih = binom.bayes(n, n.total)$lower,
            cil = binom.bayes(n, n.total)$upper) 

ms$expt <- as.factor(ms$expt)
levels(ms$expt) <- c("everyone hated vs everyone loved",
  "no one liked vs everyone liked", "everyone disliked vs eveyone liked", "everyone didn't like vs everyone liked")

qplot(valence, mean, ymax=cih, ymin=cil, 
      fill = valence, 
      stat="identity", position=position_dodge(width=.9),
      geom=c("bar","linerange"),
      data=subset(ms, judgment=="yes")) + 
  facet_wrap(~expt) +
  ylab("Proportion of judgments 'possible that all'") + 
  ylim(c(0,1)) + 
  geom_hline(yintercept=.5, lty=2) +
  guides(fill=FALSE) +
  ggtitle("comparison of exps") +
  scale_x_discrete(labels=
                     c("negative", 
                       "positive"))
```

```{r}
d_table <- table(d1$condition, d1$judgment)
chisq.test(d_table)

# a mixed model predicting participants' response as a function of condition and experiment
lmer <- glmer(judgment ~ expt * condition + (condition|subid), family=binomial, data=d1)
summary(lmer)
```